### ISSUE TITLE
boat

### ISSUE THREAD

**Issue by dfalbel** [curso-r/site-v2#2]

**Comment by williamorim** [comment]
![image](https://user-images.githubusercontent.com/8967307/45382955-3fa6d500-b5e0-11e8-9bac-16174f9eb020.png)

**Comment by williamorim** [comment]
![image](https://user-images.githubusercontent.com/8967307/45383704-5ea66680-b5e2-11e8-84df-35d56e7fcbaf.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/45968930-ac6e9600-c008-11e8-82ee-44767787535c.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/45969080-10915a00-c009-11e8-8de4-6f54506e2cb1.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/45969552-631f4600-c00a-11e8-968f-4ceea838d460.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/45971315-2013a180-c00f-11e8-8a1e-78969a0fc92c.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/45973605-53f1c580-c015-11e8-9206-d7d18b7d27c3.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/45973716-9f0bd880-c015-11e8-8d5d-1113c6db68e2.png)

**Comment by dfalbel** [comment]
![](https://aaronparecki.com/oauth-2-simplified/oauth-authorization-prompt.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/46171092-f3ad8e80-c275-11e8-8fd7-632818810f35.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/46171157-1b9cf200-c276-11e8-91d6-462ab9d2f1b7.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/46452197-d6465c00-c770-11e8-9262-c2dcdd98e9fa.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/46473446-96a26300-c7b6-11e8-8e81-4d8f504f7496.png)

**Comment by dfalbel** [comment]
![image](https://user-images.githubusercontent.com/4706822/47273449-c13c3c00-d56a-11e8-8e54-320b824f0e6f.png)
